name: Release

on:
  push:
    branches:
      - beta
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Check out repo
        uses: actions/checkout@main

      - name: Set up Node.js 16.x
        uses: actions/setup-node@main
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn --immutable

      - name: Release
        uses: changesets/action@v1
        with:
          publish: yarn release
          version: yarn version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SEEK_OSS_CI_NPM_TOKEN }}
